baseURL = "https://cdh981009.github.io/"
languageCode = "kr"
theme = "nakedMan"
title = "CryptMade"
paginate = 8

# todo: add google analytics
# googleAnalytics = ""

[markup.goldmark.renderer]
  unsafe= true

[params]
  description = "My site description"
  author = "조대호"

[[menu.main]] 
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Categories"
  url = "/categories"

[[menu.social]]
  name = "GitHub"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/cdh981009"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[related]
  threshold = 0 
  includeNewer = true
  toLower = false

  [[related.indices]]
      name = "categories"
      weight = 100

  [[related.indices]]
      name = "date"
      weight = 10