baseURL = "http://example.org/"
languageCode = "kr"
theme = "nakedMan"
title = "CryptMade"

# todo: add google analytics
# googleAnalytics = ""

[params]
  description = "My site description"
  author = "조대호"

[[menu.main]] 
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.social]]
  name = "GitHub"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/cdh981009"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"