baseURL = "https://cdh981009.github.io/"
theme = "naked-man"
title = "Crypt"
paginate = 8

languageCode = "kr"
hasCJKLanguage = true
summaryLength = 30

copyright = "&copy;{year} [cdh981009](https://cdh981009.github.io/), All Rights Reserved"

# todo: add google analytics
# googleAnalytics = ""

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "a blog of Daeho Cho"
  author = "조대호"
  mainSections = ["blog"]

[[menu.main]] 
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Categories"
  url = "/categories"
  
[[menu.main]]
  name = "Tags"
  url = "/tags"

[[menu.social]]
  name = "GitHub"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/cdh981009"

# [[menu.footer]]
#   name = "About"
#   url = "/about"

[related]
  threshold = 0 
  includeNewer = true
  toLower = false

  [[related.indices]]
      name = "categories"
      weight = 100

  [[related.indices]]
      name = "date"
      weight = 10