baseURL = "http://example.org/"
languageCode = "kr"
title = "CryptMade"
theme = "nakedMan"

# todo: add google analytics
# googleAnalytics = ""

[params]
    description = "My site description"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/cdh981009"
    pre = "<i class='fab fa-github'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"