baseURL = "https://blog.chodaeho.com/"
theme = "naked-man"
title = "Crypt"
paginate = 6

languageCode = "kr"
hasCJKLanguage = true
summaryLength = 30

copyright = "&copy;{year} [Cho Daeho](mailto:cdh981009@gmail.com), All Rights Reserved"

googleAnalytics = "UA-188922441-1"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Daeho's Crypt"
  author = "조대호"
  mainSections = ["posts"]
  startYear = 2021

[[menu.main]] 
  name = "About"
  url = "/about"
  weight = -100

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = -90

[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = -80
  
[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = -70
  
[[menu.social]]
  name = "GitHub"
  pre = "<i class='fab fa-github fa-2x'></i>"
  url = "https://github.com/cdh981009"

# [[menu.footer]]
#   name = "About"
#   url = "/about"

[related]
  threshold = 0 
  includeNewer = true
  toLower = false

  [[related.indices]]
      name = "categories"
      weight = 90

  [[related.indices]]
      name = "tags"
      weight = 100

  [[related.indices]]
      name = "date"
      weight = 10